name: go_router_examples
description: go_router examples
version: 3.0.1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  adaptive_navigation: ^0.0.4
  collection: ^1.15.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  go_router:
    path: ..
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: 
    git: https://github.com/kumsumit/shared_preferences.git
  url_launcher: 
    git: https://github.com/kumsumit/url_launcher.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
